# Generated by Django 4.2.3 on 2023-08-17 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='태그명')),
            ],
        ),
        migrations.CreateModel(
            name='Japan_clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japan_clothes', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Japan_foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japan_foods', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Japan_others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japan_others', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('thumbnail', models.ImageField(blank=True, upload_to='post', verbose_name='썸네일 이미지')),
                ('like_users', models.ManyToManyField(related_name='like_posts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='savior.hashtag', verbose_name='해시태그 목록')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='USA_clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usa_clothes', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='USA_foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usa_foods', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='USA_others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usa_others', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vietnam_clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vietnam_clothes', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vietnam_foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vietnam_foods', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vietnam_others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vietnam_others', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vietnam_others_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('number', models.IntegerField(verbose_name='숫자')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='베트남 잡화 시세 댓글 작성자')),
                ('vietnam_others_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.vietnam_others', verbose_name='베트남 잡화 시세 댓글')),
            ],
        ),
        migrations.CreateModel(
            name='Vietnam_clothes_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('number', models.IntegerField(verbose_name='숫자')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='베트남 의류 시세 댓글 작성자')),
                ('vietnam_clothes_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.vietnam_clothes', verbose_name='베트남 의류 시세 댓글')),
            ],
        ),
        migrations.CreateModel(
            name='USA_others_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('number', models.IntegerField(verbose_name='숫자')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('usa_others_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.usa_others', verbose_name='미국 잡화 시세 댓글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='미국 잡화 시세 댓글 작성자')),
            ],
        ),
        migrations.CreateModel(
            name='USA_clothes_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('number', models.IntegerField(verbose_name='숫자')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('usa_clothes_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.usa_clothes', verbose_name='미국 의류 시세 댓글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='미국 의류 시세 댓글 작성자')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='post', verbose_name='사진')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.post', verbose_name='포스트')),
            ],
        ),
        migrations.CreateModel(
            name='Japan_others_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('number', models.IntegerField(verbose_name='숫자')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('japan_others_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.japan_others', verbose_name='일본 잡화 시세 댓글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='일본 잡화 시세 댓글 작성자')),
            ],
        ),
        migrations.CreateModel(
            name='Japan_clothes_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('number', models.IntegerField(verbose_name='숫자')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('japan_clothes_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.japan_clothes', verbose_name='일본 의류 시세 댓글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='일본 의류 시세 댓글 작성자')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savior.post', verbose_name='포스트')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
